" .vimrc
" Created:  Fri 08 Aug 2008 03:15:21 PM CEST
" Modified: Sun 07 Apr 2013 12:11:57 AM CEST
" Author:   Bert Van Vreckem <bert.vanvreckem@gmail.com>
"
" Lots of inspiration comes from https://raw.github.com/teranex/dotvim/

" Load pathogen plugin manager
" Unpack plugins under .vim/bundle
execute pathogen#infect()
syntax on
filetype plugin indent on

" Editor behaviour settings {{{
set nocompatible                        " no compatibility with old-skool vi
set backspace=indent,eol,start          " define behavior of backspace key
set history=1000                        " keep more history (was 50 in Debian config)
set encoding=utf-8                      " by default set the encoding to
set fileformats=unix,dos,mac            " also read mac files correctly, just in case we are dealing with that
set nowrap                              " no line wrapping
set foldlevelstart=99                   " by default, open all folds
set foldmethod=indent                   " indent fold method by default
set mouse=a                             " enable mouse
set mousemodel=popup                    " produce pop up for right click
set scrolloff=3                         " minimal number of screen lines to keep above and below the cursor.
set sidescrolloff=3                     " minimal number of screen columns to keep next to the cursor
set sidescroll=5                        " horizontally scroll 5 characters, instead of centering the cursor
set wildmenu                            " show command line completions
set wildmode=longest:full               " complete mode for wildmenu
set wildmode+=full                      " when pressing tab a second time, fully complete
if exists("&wildignorecase")
    set wildignorecase                  " ignore case when completing filenames
endif
set linebreak                           " only wrap after words, not inside words
set completeopt=menu,longest,preview    " options for insert mode completion
"set spell                               " enable spell check by default
set tabstop=4                           " number of spaces that a tab counts for
set shiftwidth=4                        " number of spaces to use for each step of indent
set softtabstop=4                       " number of spaces that a tab counts for while editing
set shiftround                          " round the indent to a multiple of shiftwidth
set expandtab                           " expand tabs to spaces
set autoindent                          " automatically indent a new line
set formatoptions+=r                    " automatic formatting: auto insert current comment leader after enter
set virtualedit=block,onemore           " allow cursor after end of line in visual block mode and allow cursor one char after line end
set fillchars=vert:\ ,fold:-            " fill vertical splitlines with spaces instead of the ugly |-char; Default - for folds
set diffopt+=iwhite                     " diff options: ignore whitespace
set incsearch                           " while searching, immediately show first match
set ignorecase                          " ignore case in (search) patterns
set smartcase                           " when the (search) pattern contains uppercase chars, don't ignore case
set hlsearch                            " highlight all the matches for the search (disable until next search with :noh)
set directory=~/.vimswaps,.,/tmp        " where to store the swap files
set noswapfile                          " disable swap files, most of the time they are just annoying
set nobackup                            " don't make a (permanent) backup when saving files
set writebackup                         " make a (temporary) backup while saving files

if v:version > '702'
    if $VIM !~ 'vimtouch'               " check that we are not running on Android (VimTouch)
        set undofile                    " save undo history to an external file
    endif
    set undodir=~/.vimundo,.,/tmp       " where to save undo history files
    set cryptmethod=blowfish            " use stronger blowfish encryption algorithm
endif
set updatetime=500                      " wait this many milliseconds before firing the CursorHold autocmd (and write swap files)

set autoread                            " automatically reload the file when modified outside and not modified inside vim
set autowrite                           " write the modified file when switching to another file
set hidden                              " allow Vim to switch to another buffer while the current is not saved

set tags=tags;/                         " where to find the tags file: current directory and up

if exists('+autochdir')
    set autochdir                       " automatically change to the current directory when loading a file
endif

" options for sessions. These define what should be saved in a session
set sessionoptions=buffers,folds,resize,tabpages,winsize,winpos

" set the path, so we can easily open files with the gf command etc
set path+=./**;,,

" }}}

" GUI options {{{

set number                              " line numbers
set t_Co=256                            " force the terminal to use 256 colors
set showcmd                             " show the current command in the statusline
"set list                                " show special chars, such as tab and eol
"set listchars=tab:→\ ,eol:·,trail:☐,extends:❱,precedes:❰ " chars to show for list
"set showbreak=…\                        " when soft-wrapping, start lines which continue the previous line with these chars

set laststatus=2                        " always show the statusline
set title                               " set the title
set ruler                               " show cursor position in left bottom corner
set splitbelow                          " open a new horizontal window below the current window instead of above
set cursorline                          " highlight the current line
set cursorcolumn                        " highlight the current column
set display+=lastline                   " display wrapped lines at bottom instead of @ symbols
if v:version > '702'
    set colorcolumn=80,120              " show a vertical line at these positions
    set relativenumber                  " use relative line numbering
    set nonumber                        " and disable default line numbering
endif

" color scheme
let g:molokai_original=0
colorscheme molokai

" }}}

" Plugin settings {{{
"

" Timestamp
let timestamp_regexp = '\v\C%(<%(%([cC]hanged?|modified)|Modified)\s*:\s+)@<=\a+ \d{2} \a+ \d{4} \d{2}:\d{2}:\d{2}%(\s+[AP]M)?%(\s+\a+)?|Sat 06 Apr 2013 11:59:57 PM CEST'

filetype plugin indent on

" }}}

" vim: fdm=marker fdl=0
