#!/bin/bash
###############################################################################
##
# FILE:         addconsider
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 18-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addconsider	$Id: 4415f0162aa64920dec4f537cb122de294d8c60b $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) \"THING I MIGHT SOON DO\""
    echo "      Adds THING I MIGHT SOON DO, marked with priority O"
    echo "      and automatically de-prioritized after tomorrow."
    echo "      Use \"todo.sh addopportunity\" to specify a different date range."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) \"THING I MIGHT SOON DO\""
[ $# -lt 1 ] && die "$errmsg"

depriDate=$(date -d "2 days" +%F) || exit 1

"$TODO_FULL_SH" addpri O "$@" "d:${depriDate}"
