#!/bin/bash
###############################################################################
##
# FILE:         addopportunity
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 18-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addopportunity	$Id: 5792447103314eea3d70a495eccfa243ffba34ec $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) DATE \"THING I COULD DO\""
    echo "      Adds THING I COULD DO, marked with priority O"
    echo "      and automatically de-prioritized on DATE."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) DATE \"THING I COULD DO\""
[ $# -lt 2 ] && die "$errmsg"

depriDate=$(date -d "$1" +%F) || exit 1
shift

"$TODO_FULL_SH" addpri O "$@" "d:${depriDate}"
