#!/bin/bash
###############################################################################
##
# FILE:         addpri
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 21-May-2010
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addpri	$Id: 79e3b02b9ac914c0114e9a65c61357195aa4ff8d $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) PRIORITY \"THING I NEED TO DO +project @context\""
    echo "      Add a task and prioritize it in one step."
    echo ""
    exit
}

if [[ "$1" = [a-zA-Z] ]]; then
    pri=$1
    shift
fi

# Call back to the main script to add.
"$TODO_FULL_SH" add "$@" || exit $?

# Figure out the line of what we just added, and prioritize it.
item=$(sed -n '$ =' "$TODO_FILE")
"$TODO_FULL_SH" command pri "$item" $pri
