#!/bin/bash
###############################################################################
##
# FILE:         addprereq
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 19-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)addprereq	$Id: 79ffa7d8766f0b0efa33ba0c5bb10e158d899ba9 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ...] \"THING DEPENDING ON ITEM#\""
    echo "      Adds THING DEPENDING ON ITEM#, and marks them as depending on ITEM#."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ...] \"THING DEPENDING ON ITEM#\""

typeset -a depitems=()
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    depitems+=("$1")
    shift
done
[ ${#depitems} -gt 0 ] || die "$errmsg"

# Call back to the main script to add.
"$TODO_FULL_SH" add "$@" || exit $?

# Figure out the line of what we just added, and make it wait.
item=$(sed -n '$ =' "$TODO_FILE")
"$TODO_FULL_SH" wait "$item" for "${depitems[@]}"
