#!/bin/bash
###############################################################################
##
# FILE:         comment
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 07-Jan-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)comment	$Id: faccb591a9785955f9bf0783a4d279bf36d64031 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM#[, ITEM#, ITEM#, ...] COMMENT"
    echo "      Adds / appends COMMENT (with comment marker) on task(s) on line ITEM#."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...] COMMENT"
[ $# -eq 0 ] && die "$errmsg"

: ${TODOTXT_COMMENT_SYMBOL:= => }

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    items="$items $1"
    shift
done
[ "$items" ] || die "$errmsg"
[ "$*" ] || die "$errmsg"


for item in ${items//,/ }
do
    getTodo "$item"

    if [[ "$todo" =~ $TODOTXT_COMMENT_SYMBOL ]]; then
        case "$*" in
            [$SENTENCE_DELIMITERS]*)  prefix=;;
            *)                        prefix="; ";;
        esac
    else
        # Do not pass leading space; the append action adds that itself.
        prefix="${TODOTXT_COMMENT_SYMBOL# }"
    fi
    "$TODO_FULL_SH" command append $item "${prefix}$*"
done
