#!/bin/bash
###############################################################################
##
# FILE:         contextstat
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 06-Jan-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)contextstat	$Id: e7064fde147f74656d54143f96f71588b0f99c4e $	todo.txt-cli-ex
###############################################################################

export ITEM='contexts'
[ "$1" = "usage" ] && set -- "usage" "$0"
exec "$TODO_ACTIONS_DIR/birdseye+filter" "$@"
