#!/bin/bash
###############################################################################
##
# FILE:         inout
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 21-May-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)inout	$Id: f7345feb93a68d9b937e1da976ba092217dbc981 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-s] [DATE] [TERM...]"
    echo "      Shows tasks added or done today (or on [DATE])."
    echo "      If TERM specified, considers only tasks that contain TERM(s)."
    echo "      With -s, show just the summary."
    echo ""
    exit
}

isSummaryOnly=
if [ "$1" = '-s' ]; then
    isSummaryOnly=t
    shift
fi

todayDate=$(date +%F)
when='today'
whenDate=$todayDate
if [ $# -ge 1 ]; then
    # Check whether the first argument represents a date.
    whenDate=$(date -d "$1" +%F 2>/dev/null)
    if [ "$whenDate" ]; then
        when=$1
        shift
    fi
fi

# We need to check both todo.txt and the archive for tasks.
# Task added on whenDate can have already been done, so we need to look both for
# (potentially prioritized) active tasks and also done tasks added on whenDate.
addedWhen=$(TODOTXT_VERBOSE=0 "$TODO_FULL_SH" command listall "^ *[0-9]\\+ \\(\\((.) \\)\\?\\|x [0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \\)$whenDate " "$@")
doneWhen=$(TODOTXT_VERBOSE=0 "$TODO_FULL_SH" lsdone "^ *[0-9]\\+ x $whenDate " "$@")
if [ "$addedWhen" ]; then
    addedWhenNum=$(echo "$addedWhen" | wc -l)
    [ "$isSummaryOnly" ] || echo "$addedWhen"
else
    addedWhenNum=0
fi
if [ "$doneWhen" ]; then
    doneWhenNum=$(echo "$doneWhen" | wc -l)
    [ "$isSummaryOnly" ] || echo "${addedWhen:+--
}$doneWhen"
else
    doneWhenNum=0
fi
if [ $addedWhenNum -eq 0 -a $doneWhenNum -eq 0 ]; then
    if [ "$whenDate" = "$todayDate" ]; then
        echo "TODO: none added or done $when yet."
    else
        echo "TODO: none added or done $when ($whenDate)"
    fi
else
    [ "$isSummaryOnly" ] || echo '--'
    addedText=
    [ $addedWhenNum -gt 0 ] && addedText="added +${addedWhenNum}"
    doneText=
    [ $doneWhenNum -gt 0 ] && doneText="${addedText:+ / }-${doneWhenNum} done"
    echo "TODO: $when ${addedText}${doneText}"
fi
