#!/bin/bash

action=$1
flag=$2
shift

[ "$action" = "usage" ] && {
  echo "  Recently comlpeted tasks:"
  echo "    lately"
  echo "      generates a list of completed tasks during the last 7 days."
  echo "      Optional argument (integer) overrides number of days."
  echo ""
  exit
}

[ "$action" = "lately" ] && {
     python ${TODO_ACTIONS_DIR}/lately.py "$TODO_DIR" $flag
}
