#!/bin/bash
###############################################################################
##
# FILE:         latest
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 06-Jan-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)latest	$Id: a00074c11b3726b653e77a78c82dcdb21b4f02c7 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-a] [TERM...]"
    echo "    lt [TERM...]"
    echo "      Displays the last added open (all with -a) tasks"
    echo "      that contain TERM(s). Tasks without a date are ignored."
    echo ""
    exit
}

export TODOTXT_LST_ADDITIONAL_SORT_COMMAND='tail -n 10'
exec "$TODO_FULL_SH" listbydate "$@"
