#!/bin/bash
###############################################################################
##
# FILE:         listbydate
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 06-Jan-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)listbydate	$Id: 7700f1b3fd8373c64d3bd583c7d63c40188e3ab2 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [-a] [TERM...]"
    echo "      Displays open (all with -a) tasks that contain TERM(s),"
    echo "      sorted by added date. Tasks without a date are ignored."
    echo ""
    exit
}

additional_filter_command="grep -ve '^ *[0-9]\+ [xX] ' | "
if [ "$1" == '-a' ]; then
    shift
    additional_filter_command=
fi

# To sort based on the entered date, remove all tasks that do not have an
# add-date, add a dummy second column for tasks that are not prioritized, done
# or trashed, do the sort on field 3, and finally remove the dummy column again.
post_filter_command="${additional_filter_command}sed -e '/^ *[0-9]\\+ \\([xX] \|(.) \\)\\{0,1\\}[0-9]\\{2,4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} /!d' -e '/^ *[0-9]\\+ \\([xX]\\|(.)\\) /!s/^ *[0-9]\\+ /&(.) /'"
TODOTXT_SORT_COMMAND="env LC_COLLATE=C sort -f -k3,3 | sed -e 's/^\( *[0-9]\\+ \)(\.) /\\1/'${TODOTXT_LST_ADDITIONAL_SORT_COMMAND:+ | }${TODOTXT_LST_ADDITIONAL_SORT_COMMAND}"
export TODOTXT_FILTER_FUTURE_TASKS=0

_list "$TODO_FILE" "$@"
