#!/bin/bash
###############################################################################
##
# FILE:         listblockers
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 01-Feb-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)listblockers	$Id: 01ea8846ca8f86250a729602213cd0ac311ab9a7 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Lists all the wait reasons (w:... markers) in open tasks."
    echo "      If TERM specified, considers only tasks that contain TERM(s)."
    echo ""
    exit
}

eval "$(filtercommand 'cat "$TODO_FILE"' '' "$@")" | sed -e '/^[xX] /d' -e '/ w:/!d' -e 's/ w:[^ ]/\n&/g' | sed -n -e 's/^.* w:(\([^)]*\)).*$/\1/p;t' -e '/ w:[0-9]\+$/d' -e 's/^.* w:\([^ ]\+\) *$/\1/p' | sort -u
