#!/bin/bash
###############################################################################
##
# FILE:         ls
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 07-Jan-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)ls	$Id: 294f9270aec5e9c74c8f4d1eeabe20362128b61b $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all open tasks that contain TERM(s)"
    echo "      sorted by priority with line numbers."
    echo "    $(basename $0) ITEM#[, ITEM#, ...] [TERM...]"
    echo "      Displays task(s) ITEM#."
    echo ""
    exit
}

shopt -s extglob

items=
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    item=${1%,}
    item=${item#,}
    items="${items}${items:+,}$item"
    shift
done
if [ "$items" ]; then
    # Listing of task numbers is unintuitive, because the search pattern is
    # applied in the middle of alignment, when the numbers have already been
    # space- (but not zero-) aligned.
    _list "$TODO_FILE" "^ *\\(${items//,/\\|}\\) " "$@"
else
    # Consider only tasks that are not yet done.
    # The tasks are already numbered when the filter is applied, so there
    # definitely is a space in front of the marker.
    post_filter_command="grep -ve '^ *[0-9]\+ [xX] '"
    _list "$TODO_FILE" "$@"
fi
