#!/bin/bash
###############################################################################
##
# FILE:         lsac
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 01-Jun-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lsac	$Id: c243c0c3693c768b3e2e7d7f63a1229b628a46ab $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Lists all the task contexts that start with the @ sign in"
    echo "      todo.txt AND done.txt."
    echo "      If TERM specified, considers only tasks that contain TERM(s)."
    echo ""
    exit
}
TODOTXT_SOURCEVAR='("$TODO_FILE" "$DONE_FILE")' "$TODO_FULL_SH" listcon "$@"
