#!/bin/bash
###############################################################################
##
# FILE:         lsaprj
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 01-Jun-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lsaprj	$Id: 23ca32a629f3290ba4ac48d1c010dee2302b09b2 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Lists all the projects (terms that start with a + sign) in"
    echo "      todo.txt AND done.txt."
    echo "      If TERM specified, considers only tasks that contain TERM(s)."
    echo ""
    exit
}
TODOTXT_SOURCEVAR='("$TODO_FILE" "$DONE_FILE")' "$TODO_FULL_SH" listproj "$@"
