#!/bin/bash
###############################################################################
##
# FILE:         lsarchive
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 30-Dec-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lsarchive	$Id: d4ae0176a0ee4e899d026f1634813f7c8af16c72 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all archived tasks that contain TERM(s)."
    echo ""
    exit
}

# Omit the "done" highlighting in favor of the more readable alternating task
# highlighting for readability; all tasks are done, anyway.
export HIDE_COLOR_DONE=1
"$TODO_FULL_SH" listfile "${DONE_FILE:?}" "$@"
