#!/bin/bash
###############################################################################
##
# FILE:         lsdo
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 27-May-2010
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lsdo	$Id: a0ebd3b2c8cf8bbd786ab23cdf4bc48d39923ddb $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all done, but not yet archived tasks from todo.txt."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

post_filter_command="grep -e '^ *[0-9]\+ x '"
_list "$TODO_FILE" "$@"
