#!/bin/bash
###############################################################################
##
# FILE:         lspriprj
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 13-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lspriprj	$Id: 41c51cb2ad5dfe2b1c6540fbaf42d169dd1fc7e5 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [PRIORITIES] [TERM...]"
    echo "      Lists all the projects that appear in tasks prioritized PRIORITIES."
    echo "      PRIORITIES can be a single one (A) or a range (A-C)."
    echo "      If no PRIORITIES specified, all prioritized tasks are used."
    echo "      If TERM specified, considers only prioritized tasks that contain TERM(s)."
    echo ""
    exit
}

TODOTXT_VERBOSE=0 TODOTXT_PLAIN=1 "$TODO_FULL_SH" listpri "$@" | grep -o '[^ ]*+[^ ]\+' | grep '^+' | sort -u
