#!/bin/bash
###############################################################################
##
# FILE:         lsstarted
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 20-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lsstarted	$Id: 4d18227f02e621a83d8c7458eb096dd5916f0ccb $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all tasks being worked on (priority P) in todo.txt."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

exec "$TODO_FULL_SH" lspri P "$@"
