#!/bin/bash
###############################################################################
##
# FILE:         lstrashable
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 24-Feb-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)lstrashable	$Id: d0486f5fa9aae39cc6ecfadf8def64440171fdf6 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [TERM...]"
    echo "      Displays all to-be-trashed tasks from todo.txt."
    echo "      If TERM specified, lists only tasks that contain TERM(s)."
    echo ""
    exit
}

# Omit the "trashed" highlighting in favor of the more readable alternating task
# highlighting for readability; all tasks are trashed, anyway.
# This only works for "todo.sh ls", but we invoke _list() directly.
#export HIDE_COLOR_TRASH=1
unset COLOR_TRASH

post_filter_command="grep -e '^ *[0-9]\+ X '"
_list "$TODO_FILE" "$@"
