#!/bin/bash
###############################################################################
##
# FILE:         sh
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 20-Jun-2013
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2013 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)sh	$Id: f1bb02553043ab0b7aec715c838098e3949f950a $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0)"
    echo "      Enter a bunch of todo.sh commands interactively."
    echo ""
    exit
}

while read -p "todo> " line; do
    if [ "x$line" != "xexit" ]; then
        "$TODO_FULL_SH" $line
    else
        echo "bye"
        break
    fi
done
