#!/bin/bash
###############################################################################
##
# FILE:         start
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 18-Apr-2012
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)start	$Id: 968871364f5941330b50a24282ae2d3fcf726ad5 $	todo.txt-cli-ex
###############################################################################

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [on DATE|DATE-] [until DATE|-DATE] ITEM#[, ITEM#, ...] [COMMENT]"
    echo "    $(basename $0) ITEM#[, ITEM#, ...] [on DATE|DATE-] [until DATE|-DATE] [COMMENT]"
    echo "      Marks task(s) on line ITEM# as being worked on (priority P) in todo.txt,"
    echo "      optionally appending COMMENT."
    echo ""
    exit
}

errmsg="usage: $TODO_SH $(basename $0) ITEM#[, ITEM#, ITEM#, ...] [on DATE|DATE-] [until DATE|-DATE] [COMMENT]"
[ $# -eq 0 ] && die "$errmsg"

"$TODO_FULL_SH" pri P "$@"
