#! /usr/bin/bash
#
# Author:   Bert Van Vreckem <bert.vanvreckem@gmail.com>
#
# 

set -e # abort on nonzero exitstatus
set -u # abort on unbound variable

#{{{ Variables

#}}}
#{{{ Functions

usage() {
cat << _EOF_
Usage: ${0} 

_EOF_
}

#}}}
#{{{ Command line parsing

if [[ "$#" -ne "1" ]]; then
    echo "Expected 1 argument, got $#" >&2
    usage
    exit 2
fi

#}}}
# Script proper


# cursor: 5 del
