#!/bin/bash
#
# Created:  TIMESTAMP
# Modified: TIMESTAMP
# Author:   Bert Van Vreckem <bert.vanvreckem@gmail.com>
#

set -e # abort on nonzero exitstatus
set -u # abort on unbound variable

# cursor: 11 del
