#!/bin/bash
###############################################################################
##
# FILE:         colorFutureTasks
# PRODUCT:      todo.txt-cli-ex
# AUTHOR:       Ingo Karkat <ingo@karkat.de>
# DATE CREATED: 27-Nov-2011
#
###############################################################################
# CONTENTS:
#
# REMARKS:
#
# COPYRIGHT: (C) 2010-2012 Ingo Karkat
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License.
#   See http://www.gnu.org/copyleft/gpl.txt
#
# @(#)colorFutureTasks	$Id: 7d18b1b9b2ddc0ffb4c2e4a8e936ff2d15409097 $	todo.txt-cli-ex
###############################################################################

export TODOTXT_FILTER_FUTURE_TASKS=${TODOTXT_FILTER_FUTURE_TASKS:-1}

if [ $TODOTXT_PLAIN -eq 0 ]; then
    # Note: Highlightings that set the background color (\\033[4...) must have
    # $DEFAULT prepended to reset any foreground highlighting from a predecessor
    # element when it is used to continue the line highlighting.

    if [ ${TERM_COLORS:-0} -ge 256 ]; then
        export COLOR_DUE_FUTURE=${COLOR_DUE_FUTURE-$DEFAULT'\\033[48;5;195m'}
        export COLOR_DUE_TODAY=${COLOR_DUE_TODAY-$DEFAULT'\\033[48;5;190m'}
        export COLOR_DUE_1DAY=${COLOR_DUE_1DAY-$DEFAULT'\\033[48;5;193m'}
        export COLOR_DUE_2DAY=${COLOR_DUE_2DAY-$DEFAULT'\\033[48;5;230m'}
        export COLOR_DUE_3DAY=${COLOR_DUE_3DAY-$DEFAULT'\\033[48;5;229m'}
        export COLOR_DUE_1WEEK=${COLOR_DUE_1WEEK-$DEFAULT'\\033[48;5;186m'}
        export COLOR_DUE_2WEEK=${COLOR_DUE_2WEEK-$DEFAULT'\\033[48;5;178m'}
        export COLOR_DUE_OLDEST=${COLOR_DUE_OLDEST-$DEFAULT'\\033[48;5;138m'}

        export COLOR_UNTIL_FUTURE=${COLOR_UNTIL_FUTURE-$DEFAULT'\\033[48;5;196m'}
        export COLOR_UNTIL_TODAY=${COLOR_UNTIL_TODAY-$DEFAULT'\\033[48;5;202m'}
        export COLOR_UNTIL_1DAY=${COLOR_UNTIL_1DAY-$DEFAULT'\\033[48;5;208m'}
        export COLOR_UNTIL_2DAY=${COLOR_UNTIL_2DAY-$DEFAULT'\\033[48;5;214m'}
        export COLOR_UNTIL_3DAY=${COLOR_UNTIL_3DAY-$DEFAULT'\\033[48;5;220m'}
    else
        export COLOR_DUE_TODAY=${COLOR_DUE_TODAY-$DEFAULT'\\033[42m'}
        export COLOR_DUE_3DAY=${COLOR_DUE_3DAY-$DEFAULT'\\033[47m'}
        export COLOR_DUE_2WEEK=${COLOR_DUE_2WEEK-$DEFAULT'\\033[43m'}
        export COLOR_DUE_OLDEST=${COLOR_DUE_OLDEST-$DEFAULT'\\033[45m'}

        export COLOR_UNTIL_FUTURE=${COLOR_UNTIL_FUTURE-$DEFAULT'\\033[01;37;41m'}
        export COLOR_UNTIL_TODAY=${COLOR_UNTIL_TODAY-$DEFAULT'\\033[37;41m'}
        export COLOR_UNTIL_3DAY=${COLOR_UNTIL_3DAY-$DEFAULT'\\033[43m'}
    fi

    awk --re-interval -v date=$1 '
function getThreshold(date) {
    if (date == "") {
        return mktime(strftime("%Y %m %d 00 00 00", systime()))
    } else {
        return mktime(gensub(/([0-9]{4})-([0-9]{2})-([0-9]{2})/, "\\1 \\2 \\3 00 00 00", "", date))
    }
}
function hasHighlight(colorVar) {
    return (ENVIRON[colorVar] != "")
}
function highlight(colorVar,      color) {
    color = ENVIRON[colorVar]
    gsub(/\\+033/, "\033", color)
    return color
}
function highlightend(colorVar, defaultColor,      color) {
    color = highlight(colorVar "_END")
    return (color == "" ? (defaultColor == "" ? highlight("DEFAULT") : defaultColor) : color)
}
function getLineColor(      hl) {
    if (match($0, /[0-9]+ /) > 1) {
        return substr($0, 1, RSTART - 1)
    } else {
        return ""
    }
}
function getSpanClass(daySpan, what,      class) {
    # We do not want the fallback to older span classes for future due dates, so
    # they are handled specially.
    if (daySpan < 0) {
        class = "COLOR_" what "_FUTURE"
        return (ENVIRON[class] == "" ? "" : class)
    }

    # Find the bucket where the span falls into...
    for (i = 1; i <= spanNum; i++) {
        if (daySpan < spanNumbers[i])
            break
    }

    # ...then find the next bucket for which an actual color definition actually
    # exists, looking into progressively larger spans of time. (I.e. if there is
    # no special highlighting for "due in 3 days", we use the highlighting for
    # "due in 1 week" instead.)
    for (j = i; j <= spanNum + 1; j++) {
        class = "COLOR_" what "_" spanNames[j]
        if (ENVIRON[class] != "")
            return class
    }
}
BEGIN {
    spanNum =   split("         1    2    3     7    14    21     30     60     91   365   730  1095   1461", spanNumbers)
                split("TODAY 1DAY 2DAY 3DAY 1WEEK 2WEEK 3WEEK 1MONTH 2MONTH 3MONTH 1YEAR 2YEAR 3YEAR OLDEST", spanNames)

    threshold = getThreshold(date)
}
# Existing line highlightings (i.e. prioritized or done tasks) have precedence
# over any time-based rules.
{
    lineColor = getLineColor()
    netTask = substr($0, length(lineColor) + 1)
    if (match(netTask, /^[0-9]+ x /)) {
        # Do not process done tasks.
        print
        next
    } else if (match(netTask, /^[0-9]+ X /)) {
        # Highlight trashed tasks, and do not process them further.
        print highlight("COLOR_TRASH") $0 highlight("DEFAULT")
        next
    }
}
# Highlight tasks with a do-until date. This has precedence over a due date.
/ [uz]:[0-9]{4}-[0-9]{2}-[0-9]{2}/ {
    date = mktime(gensub(/^.* [uz]:([0-9]{4})-([0-9]{2})-([0-9]{2})([^0-9].*)?$/, "\\1 \\2 \\3 00 00 00", ""))

    # Highlight tasks with a do-until date, depending on how long until the date.
    daySpan = int((date - threshold) / 86400)
    untilClass = getSpanClass(daySpan, "UNTIL")
    if (hasHighlight(untilClass)) {
        if (lineColor == "") {
            # No existing line color, apply to entire line.
            lineColor = highlight(untilClass)
            $0 = highlight(untilClass) $0 highlightend(untilClass, "")
        } else {
            # The line is already colored, only highlight the do-until date itself.
            $0 = gensub(/ ([uz]:[0-9]{4}-[0-9]{2}-[0-9]{2})/, " " highlight(untilClass) "\\1" highlightend(untilClass, lineColor), "")
        }
    }
}
# Filter out tasks due in the future, highlight the time since tasks have become
# due.
/ t:[0-9]{4}-[0-9]{2}-[0-9]{2}/ {
    date = mktime(gensub(/^.* t:([0-9]{4})-([0-9]{2})-([0-9]{2})([^0-9].*)?$/, "\\1 \\2 \\3 00 00 00", ""))
    if (ENVIRON["TODOTXT_FILTER_FUTURE_TASKS"] > 0 && date > threshold) {
        # Suppress tasks that are scheduled in the future.
        next
    } else if (ENVIRON["TODOTXT_FILTER_FUTURE_TASKS"] < 0 && date <= threshold) {
        # Suppress tasks that are have already been scheduled.
        next
    }

    # Highlight scheduled tasks, depending on how long they are due now.
    daySpan = int((threshold - date) / 86400)
    dueClass = getSpanClass(daySpan, "DUE")
    if (hasHighlight(dueClass)) {
        if (lineColor == "") {
            # No existing line color, apply to entire line.
            lineColor = highlight(dueClass)
            $0 = highlight(dueClass) $0 highlightend(dueClass, "")
        } else {
            # The line is already colored, only highlight the due date itself.
            $0 = gensub(/ (t:[0-9]{4}-[0-9]{2}-[0-9]{2})/, " " highlight(dueClass) "\\1" highlightend(dueClass, lineColor), "")
        }
    }
}
{ print }
'
elif [ $TODOTXT_FILTER_FUTURE_TASKS -ne 0 ]; then
    awk --re-interval -v date=$1 '
function getThreshold(date) {
    if (date == "") {
        return mktime(strftime("%Y %m %d 00 00 00", systime()))
    } else {
        return mktime(gensub(/([0-9]{4})-([0-9]{2})-([0-9]{2})/, "\\1 \\2 \\3 00 00 00", "", date))
    }
}
BEGIN {
    threshold = getThreshold(date)
}
/^[0-9]+ [xX] / {
    # Do not process done tasks.
    print
    next
}
/ t:[0-9]{4}-[0-9]{2}-[0-9]{2}/ {
    date = mktime(gensub(/^.* t:([0-9]{4})-([0-9]{2})-([0-9]{2})([^0-9].*)?$/, "\\1 \\2 \\3 00 00 00", ""))
    if (date > threshold) {
        # Suppress tasks that are scheduled in the future.
        next
    }
}
{ print }
'
else
    cat
fi
