#!/bin/bash


COLOR_CONTEXT=$Green
COLOR_PROJECT=$Blue
COLOR_DATE=$Purple
# Force gawk to behave posixly. Comment out if you get an error about
# no such option -W.
AWK_OPTIONS="-W posix"
if [ "$TODOTXT_PLAIN" -eq "0" ]; then
    awk $AWK_OPTIONS "
        { color = \"$D\" }
        /\(A\)/ { color = \"$PRI_A\" }
        /\(B\)/ { color = \"$PRI_B\" }
        /\(C\)/ { color = \"$PRI_C\" }
        /\([D-Z]\)/ { color = \"$PRI_X\" }
        {
            gsub(/@[^ ]*/, \"$COLOR_CONTEXT&\" color);
            gsub(/\+[^ ]*/, \"$COLOR_PROJECT&\" color);
            sub(/[0-9]{4}(-[0-9]{2}){2}/, \"$COLOR_DATE&\" color);
            print
        }
    "
else
    cat
fi
